[package]
name = "analytics-real-time"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = "0.8" 
chrono = "0.4" 
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4" 